# Source: acm-charts/templates/namespaces/tqa/pu10/repository-secrets.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: 
     new: tag
  name: default
  namespace: pu10
imagePullSecrets:
- name: secret1
#- name: gcr-json-key-us

